- name: Change OSTree remote repo for mkex
  become: true
  block:
    - name: Check if the mkex OSTree remote repo exists
      ansible.builtin.command: ostree remote list
      register: remote_list

    - name: Remove the mkex OSTree remote repo if it exists
      ansible.builtin.command: ostree remote delete mkex
      when: "'mkex' in remote_list.stdout"

    - name: Set the MKEx OSTree remote repo
      ansible.builtin.command: ostree remote add mkex --no-gpg-verify {{ ostree_repo_url }}
  when: ostree_repo_url is defined and ostree_repo_url | length > 0
