# TODO: add more checks as described in https://docs.mirantis.com/mke/3.7/ops/upgrades-and-migrations/upgrade-mke/verify-environment.html
- name: MKE-native upgrade check
  ansible.builtin.command:
    argv:
      - docker
      - run
      - --rm
      - --security-opt
      - label=disable
      - -v
      - /var/run/docker.sock:/var/run/docker.sock
      - "mirantis/ucp:{{ target_mke_version.stdout }}"
      - upgrade
      - checks
      - "{{ mke_upgrade_check_flags | join(' ') }}"
  run_once: true
