- name: Stop docker service
  ansible.builtin.systemd_service:
    name: docker
    state: stopped
  when: swarm_status.stdout == "active"
  become: true

- name: Backup Swarm directory
  ansible.builtin.shell: tar -cvzf '/tmp/swarm-{{ current_engine_version.stdout }}-backup-{{ hostvars["localhost"]["start_timestamp"] }}.tar.tgz' /var/lib/docker/swarm/
  become: true

- name: Start docker service
  ansible.builtin.systemd_service:
    name: docker
    state: started
  become: true
