- name: Check if OSTree ref exists
  hosts: all
  gather_facts: false
  vars_files:
    - upgrade-vars.yml
  tasks:
    - ansible.builtin.include_tasks: tasks/ostree-check-if-ref-exists-task.yml
      when: "ostree_ref_name != ''"

- name: Setup up Docker on remote hosts
  ansible.builtin.import_playbook: mcr-setup-docker.yml

- name: Open required MKE ports
  gather_facts: false
  hosts: all
  tasks:
    - ansible.builtin.include_tasks: tasks/mke-open-ports-tasks.yml

- name: Backup MKE before upgrade
  ansible.builtin.import_playbook: mke-backup-playbook.yml
- name: Upgrade OS with OSTree for managers
  hosts: managers
  vars_files:
    - upgrade-vars.yml
  serial: 1
  gather_facts: false
  tasks:
    - ansible.builtin.include_tasks: tasks/ostree-upgrade-tasks.yml

- name: Upgrade OS with OSTree for workers
  hosts: workers
  vars_files:
    - common-vars.yml
    - upgrade-vars.yml
  serial: "{{ upgrade_worker_batch_size | default(1) }}"
  gather_facts: false
  tasks:
    - name: Docker Swarm Drain 'workers'
      ansible.builtin.include_tasks:
        file: tasks/swarm-drain-nodes.yml
    - name: OSTree upgrade
      ansible.builtin.include_tasks:
        file: tasks/ostree-upgrade-tasks.yml
    - name: Docker Swarm Uncordon 'workers'
      ansible.builtin.include_tasks:
        file: tasks/swarm-uncordon-nodes.yml

- name: Pre-upgrade checks
  hosts: all
  gather_facts: false
  vars_files:
    - upgrade-vars.yml
  tasks:
    - ansible.builtin.include_tasks: tasks/helpers/get_current_mke_version.yml
    - ansible.builtin.include_tasks: tasks/helpers/get_target_mke_version.yml
    - ansible.builtin.include_tasks: tasks/mke-preupgrade-tasks.yml
      when: "ostree_ref_name != ''"

- name: Upgrade MKE
  hosts: managers
  gather_facts: false
  vars_files:
    - upgrade-vars.yml
  tasks:
    - ansible.builtin.include_tasks: tasks/helpers/get_current_mke_version.yml
    - ansible.builtin.include_tasks: tasks/helpers/get_target_mke_version.yml
    - name: Run upgrade MKE tasks
      ansible.builtin.include_tasks: tasks/mke-upgrade-tasks.yml
      when: target_mke_version.stdout > current_mke_version.stdout or ostree_ref_name != ''
