#cloud-config
hostname: ${hostname}
create_hostname_file: true
fqdn: ${hostname}
users:
  - name: ${user}
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ${ssh_key}
runcmd:
  - 'rm /etc/machine-id'
  - 'rm /var/lib/dbus/machine-id'
  - 'dbus-uuidgen --ensure'
  - 'systemd-machine-id-setup'
  - 'sudo grep docker /usr/lib/group | sudo tee -a /etc/group'
  - 'sudo usermod -aG docker ${user}'
    #  - 'growpart /dev/sda 3'
    #  - 'lvresize -l +100%FREE /dev/mkex/root'
    #  - 'su root -c "unshare --mount"'
    #  - 'su root -c "mount -o remount,rw /sysroot"'
    #  - 'su root -c "xfs_growfs /sysroot"'
